FROM node:20-alpine

WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/frontend/package.json apps/frontend/package.json
COPY apps/backend/package.json apps/backend/package.json
COPY apps/backend/prisma apps/backend/prisma

RUN pnpm install --frozen-lockfile

CMD ["pnpm", "--filter", "frontend", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
